---
- name: Installer les fonctionnalités DHCP et Active Directory
  hosts: windows-server
  gather_facts: no
  become: yes

  vars:
    ad_password: "Winser19!"
    domain_name: "lille.local"
    dhcp_scope_start: "192.168.5.100"
    dhcp_scope_end: "192.168.5.140"
    dns_server: "192.168.3.1"

  tasks:
  - name: Installer le rôle DHCP
    win_feature:
      name: DHCP
      state: present

  - name: Configurer la portée DHCP
    win_dhcp_scope:
      name: "Ma plage de DHCP"
      state: present
      subnet: "192.168.5.0"
      mask: "255.255.255.0"
      start_ip: "{{ dhcp_scope_start }}"
      end_ip: "{{ dhcp_scope_end }}"
      gateway: "192.168.3.1"
      dns: "{{ dns_server }}"
      lease_duration: 8
      domain_name: "{{ domain_name }}"

  - name: Installer le rôle Active Directory
    win_feature:
      name: AD-Domain-Services
      state: present

  - name: Configurer l'Active Directory
    win_domain:
      dns_domain_name: "{{ domain_name }}"
      safe_mode_password: "{{ ad_password }}"
      domain_admin_user: "administrator"
      domain_admin_password: "{{ ad_password }}"
      state: domain
      create_dns_delegation: no
      domain_level: 7
      install_dns: yes
      safe_mode_admin_password: "{{ ad_password }}"
      force_reboot: yes
