- name: Récupérer et executer un docker compose depuis Git
  hosts: dev
  become: true
  vars:
    path: "/home/formation/docker-compose/"
  tasks:
    - name: Récupérer le docker compose
      git: 
        repo: https://github.com/hugowamser/Projet_Devops_equipe2.git
        dest: "{{path}}"
      register: git_clone

    - name: Executer le docker compose
      docker_compose:
        project_src: 
          - "{{path}}/Docker/mariadb/docker-compose.yml"
          - 
        state: present
